"""Generate .claude/rules/guardian-*.md files from learned patterns."""

import os
import re

GUARDIAN_MARKER = "Auto-generated by claude-guardian"

# Map pattern names to glob patterns and human-readable rule content
RULE_TEMPLATES = {
    "naming": {
        "title": "Naming Convention",
        "body": "- Files in `{dir_key}/` use **{dominant_value}** naming\n- Detected: {frequency}/{sample_size} files follow this convention",
    },
    "structure:tests": {
        "title": "Test File Location",
        "body": "- Tests use **{dominant_value}** pattern\n- Detected: {frequency}/{sample_size} test files follow this convention",
    },
    "import:js_style": {
        "title": "JavaScript/TypeScript Import Style",
        "body": "- Prefer **{dominant_value}** imports\n- Detected: {frequency}/{sample_size} imports follow this style",
    },
    "import:py_style": {
        "title": "Python Import Style",
        "body": "- Prefer **{dominant_value}** imports\n- Detected: {frequency}/{sample_size} imports follow this style",
    },
    "import:export_style": {
        "title": "Export Style",
        "body": "- Prefer **{dominant_value}** exports\n- Detected: {frequency}/{sample_size} exports follow this style",
    },
    "pattern:error_handling": {
        "title": "Error Handling Pattern",
        "body": "- Prefer **{dominant_value}** for error handling\n- Detected: {frequency}/{sample_size} occurrences follow this pattern",
    },
}


def _pattern_to_globs(pattern):
    """Convert a pattern result to appropriate glob patterns."""
    name = pattern["pattern_name"]

    if name.startswith("naming:"):
        dir_key = pattern.get("dir_key", "")
        return [f"**/{dir_key}/**"]

    if name == "structure:tests":
        return ["**/*.test.*", "**/*.spec.*", "**/__tests__/**"]

    if name.startswith("import:js"):
        return ["**/*.{js,jsx,ts,tsx}"]

    if name.startswith("import:py"):
        return ["**/*.py"]

    if name.startswith("import:export"):
        return ["**/*.{js,jsx,ts,tsx}"]

    if name.startswith("pattern:"):
        return ["**/*.{js,jsx,ts,tsx,py}"]

    if name.startswith("structure:"):
        ext = name.split(":")[1]
        return [f"**/*{ext}"]

    return ["**/*"]


def _get_template_key(pattern_name):
    """Map a pattern name to its template key."""
    if pattern_name.startswith("naming:"):
        return "naming"
    return pattern_name


def _is_user_edited(filepath):
    """Check if a rule file was manually edited (no longer has our marker)."""
    if not os.path.exists(filepath):
        return False
    try:
        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read(500)
        return GUARDIAN_MARKER not in content
    except OSError:
        return False


def _sanitize_filename(name):
    """Convert pattern name to safe filename."""
    return re.sub(r"[^a-zA-Z0-9_-]", "-", name)


def generate_rules(patterns, project_root):
    """Generate .claude/rules/guardian-*.md files for patterns that meet threshold."""
    rules_dir = os.path.join(project_root, ".claude", "rules")
    os.makedirs(rules_dir, exist_ok=True)

    generated = []

    for p in patterns:
        confidence = p.get("confidence", 0)
        sample_size = p.get("sample_size", 0)

        # Only generate rules for high-confidence patterns
        if confidence < 0.85 or sample_size < 15:
            continue

        pattern_name = p["pattern_name"]
        safe_name = _sanitize_filename(pattern_name)
        filepath = os.path.join(rules_dir, f"guardian-{safe_name}.md")

        # Never overwrite user-edited rules
        if _is_user_edited(filepath):
            continue

        template_key = _get_template_key(pattern_name)
        template = RULE_TEMPLATES.get(template_key)
        if not template:
            continue

        globs = _pattern_to_globs(p)
        globs_str = json.dumps(globs) if len(globs) > 1 else json.dumps(globs)

        conf_pct = int(confidence * 100)
        body = template["body"].format(**p)

        content = f"""---
description: "{GUARDIAN_MARKER} (confidence: {conf_pct}%, samples: {sample_size})"
globs: {globs_str}
---
# {template["title"]}
{body}
"""

        try:
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(content)
            generated.append(filepath)
        except OSError:
            continue

    return generated


# Need json for globs_str
import json
